Remove `__pycache__` and update `.gitignore`
Coding-Cactus/Draughts pull request #1
Opened 2022-09-02 14:44 UTC by BD103

This repo popped up in my feed, figured I would check it out. :)

2022-09-04 20:49 UTC, Coding-Cactus requested changes
Loads of unnecessary stuff

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +*.spec
Don't want to ignore .spec file. Would like contributors to be able to test with correct publish settings.

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Django stuff:
Not using django

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Flask stuff:
Not using flask

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Scrapy stuff:
Not using scrapy

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Sphinx documentation
Not using sphinx

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# PyBuilder
Not using pybuilder

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Jupyter Notebook
Not using jupyter notebook

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# IPython
Not using Ipython

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# pyenv
No need to keep commented out stuff.

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +.pdm.toml
Not using pdm

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Celery stuff
Not using celery

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# SageMath parsed files
Not using sagemath

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Unit test / coverage reports
Not using any unit tests 😜

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Rope project settings
Not using rope project

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# mkdocs documentation
Not using mkdocs

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# mypy
Not using mypy

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Pyre type checker
Not using pyre

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# pytype static type analyzer
Not using pytype

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Translations
Not using these

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# Distribution / packaging
Only need to ignore build/, dist/

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +lib/
DEFINITELY don't want to ignore lib/

2022-09-04 20:49 UTC, Coding-Cactus commented on .gitignore
> +# C extensions
Not using any c extensions

2022-09-04 22:20 UTC, BD103 commented
Wow that's a lot of changes requested. I copied the `.gitignore` file from [github/gitignore](https://github.com/github/gitignore). Usually I just keep the defaults, but you seem to not want that. I removed the things you requested.

2022-09-07 19:01 UTC, Coding-Cactus approved these changes

2022-09-07 19:03 UTC, merged